# Generated by Django 5.2.7 on 2025-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_paie', '0002_alter_employe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepaie',
            name='fichier_pdf',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
