# Generated by Django 5.2.7 on 2025-12-10 12:46

from django.db import migrations
from django.contrib.auth.hashers import make_password

def populate_employees_with_users(apps, schema_editor):
    Employe = apps.get_model('fiche_paie', 'Employe')
    User = apps.get_model('auth', 'User')
    for employee in Employe.objects.filter(user__isnull=True):
        username = employee.matricule
        user, user_created = User.objects.get_or_create(
            username=username,
            defaults={
                'email': employee.email,
                'first_name': employee.prenom,
                'last_name': employee.nom,
            }
        )
        if user_created:
            user.password = make_password('defaultpassword2025')
            user.save()
        employee.user = user
        employee.save()

def remove_user_from_employees(apps, schema_editor):
    # Reverse migration: not needed, but for completeness
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fiche_paie', '0004_employe_user'),
        migrations.swappable_dependency('auth.user'),
    ]

    operations = [
        migrations.RunPython(populate_employees_with_users, remove_user_from_employees),
    ]
