# Generated by Django 5.2.7 on 2025-11-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_paie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employe', 'verbose_name_plural': 'Employes'},
        ),
    ]
